name: Delete a distribution from DeployGate
author: Jumpei Matsuda
description: An action to delete a *distribution* from DeployGate on branch-delete
inputs:
  api_token:
    descritpion: An api token of DeployGate. Required but this can be passed through environment variables and environment variable is preferred.
    required: false
  app_owner_name:
    desciription: An app owner name on DeployGate. Required but this can be passed through environment variables.
    required: false
  app_id:
    descritpion: A application id (package name/bundle identifier) of an app which may have a distribution to delete. Required but this can be passed through environment variables.
    required: false
  platform:
    description: A platform name whic is either Andoird or iOS.
    required: true
    default: 'android'
  distribution_name:
    description: A name of a distribution to delete. Use branch name unless specified.
    required: false
  exclude_pattern:
    description: A pattern to ignore names which you do not want to destroy. The syntax is based on Bash 4.x
    required: false
    default: ''
  ignore_api_failure:
    description: Specify true if this action should not exit with any failure status when calling DeployGate API.
    require: false
    default: false
runs:
  using: 'docker'
  image: './Dockerfile'
branding:
  color: 'red'
  icon: 'trash'