name: For testing

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Upload an app and create a distribution
      run: 'curl -X POST -H "Authorization: token ${{ secrets.DEPLOYGATE_API_TOKEN }}" "https://deploygate.com/api/users/${{ secrets.TEST_USER_NAME }}/apps" -F file=@./.github/workflows/app.apk -F distribution_name=test_via_action'
    - uses: ./
      with:
        app_owner_name: ${{ secrets.TEST_USER_NAME }}
        platform: android
        app_id: ${{ secrets.TEST_APPLICATION_ID }}
        api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
        distribution_name: test_via_action
